In [1]:
from datasets import load_dataset
import pandas as pd

In [3]:
kz_dataset = load_dataset(
    "shyngys879/Kazakh-Wiki-RAG-Dataset"
)

Generating train split: 0 examples [00:00, ? examples/s]

DatasetGenerationCastError: An error occurred while generating the dataset

All the data files must have the same columns, but at some point there are 1 new columns ({'negative'})

This happened while the csv dataset builder was generating data using

hf://datasets/shyngys879/Kazakh-Wiki-RAG-Dataset/train_triplets.csv (at revision 3967b4f235de21f9da7c0e05114483538d9954cf), [C:\Users\nurs\.cache\huggingface\hub\datasets--shyngys879--Kazakh-Wiki-RAG-Dataset\snapshots\3967b4f235de21f9da7c0e05114483538d9954cf\train.csv (origin=hf://datasets/shyngys879/Kazakh-Wiki-RAG-Dataset@3967b4f235de21f9da7c0e05114483538d9954cf/train.csv), C:\Users\nurs\.cache\huggingface\hub\datasets--shyngys879--Kazakh-Wiki-RAG-Dataset\snapshots\3967b4f235de21f9da7c0e05114483538d9954cf\train_pairs.csv (origin=hf://datasets/shyngys879/Kazakh-Wiki-RAG-Dataset@3967b4f235de21f9da7c0e05114483538d9954cf/train_pairs.csv), C:\Users\nurs\.cache\huggingface\hub\datasets--shyngys879--Kazakh-Wiki-RAG-Dataset\snapshots\3967b4f235de21f9da7c0e05114483538d9954cf\train_triplets.csv (origin=hf://datasets/shyngys879/Kazakh-Wiki-RAG-Dataset@3967b4f235de21f9da7c0e05114483538d9954cf/train_triplets.csv)]

Please either edit the data files to have matching columns, or separate them into different configurations (see docs at https://hf.co/docs/hub/datasets-manual-configuration#multiple-configurations)

In [5]:
base_url = "hf://datasets/shyngys879/Kazakh-Wiki-RAG-Dataset"

kz_train = pd.read_csv(f"{base_url}/train.csv")
kz_pairs = pd.read_csv(f"{base_url}/train_pairs.csv")
kz_triplets = pd.read_csv(f"{base_url}/train_triplets.csv")

print("train:", kz_train.shape)
print("pairs:", kz_pairs.shape)
print("triplets:", kz_triplets.shape)

train: (17320, 3)
pairs: (17320, 3)
triplets: (17320, 4)

In [6]:
print("TRAIN")
print(kz_train.columns.tolist())

print("\nPAIRS")
print(kz_pairs.columns.tolist())

print("\nTRIPLETS")
print(kz_triplets.columns.tolist())

TRAIN
['anchor', 'positive', 'source']

PAIRS
['anchor', 'positive', 'source']

TRIPLETS
['anchor', 'positive', 'negative', 'source']

In [7]:
kz_triplets.head()

,anchor,positive,negative,source
0,Жерлеу рәсімін жасауға мүмкіндік болмаған жағд...,Жерлеу рәсімідерін жасауға мүмкіндік болмайтын...,Бұл анықтамада егеменді билік және мемлекеттік...,wiki_llm
1,Шерік деген атаудың мағынасы,Шерік — жауынгер атауы. Халық жасағындағы жауы...,Ашық экономика - сыртқы дүниемен кең ауқымды с...,wiki_llm
2,Фрэнсис Крик және Джеймс Уотсон кімдер,1953 жылы ағылшын ғалымы Фрэнсис Крик және аме...,Капител ( – заттың ұшар басы) – тіреу бағаныны...,wiki_llm
3,КСРО ғылым академиясының Металлургия институты...,Орал политехникалық институтын бітірген (Екате...,"Кен денелері ұзындығы 40-100 м, қалыңдығы 0,5-...",wiki_llm
4,Христофор Колумб қай елдердің аралдарында өмір...,Христофор Колумб (; ; 31 қазан 1451 жыл – 20 м...,1992 жылдан Ақмола педагогикалық институтында ...,wiki_llm

In [8]:
kz_triplets["anchor_len"] = kz_triplets["anchor"].str.len()
kz_triplets["positive_len"] = kz_triplets["positive"].str.len()
kz_triplets["negative_len"] = kz_triplets["negative"].str.len()

kz_triplets[
    ["anchor_len", "positive_len", "negative_len"]
].describe(
    percentiles=[0.5, 0.75, 0.9, 0.95, 0.99]
)

         anchor_len  positive_len  negative_len
count  17320.000000  17320.000000  17320.000000
mean      38.403868    354.957159    353.474134
std       11.735051    160.789496    159.983020
min        9.000000    120.000000    120.000000
50%       38.000000    306.000000    306.000000
75%       45.000000    507.000000    503.000000
90%       53.000000    607.000000    605.000000
95%       59.000000    629.000000    629.000000
99%       72.000000    646.000000    646.810000
max      114.000000    650.000000    650.000000

In [9]:
print("Anchor duplicates:", kz_triplets["anchor"].duplicated().sum())
print("Positive duplicates:", kz_triplets["positive"].duplicated().sum())
print("Negative duplicates:", kz_triplets["negative"].duplicated().sum())

Anchor duplicates: 0
Positive duplicates: 0
Negative duplicates: 6119